### PR TITLE
feat: allow for live item updates (false by default)

### PR DESCRIPTION
**Pull request by emilesilvis**
https://developers.webflow.com/#update-live-collection-item

### CODE REVIEW

**Comment by phoet** [comment]
Does this also work while passing the live parameter as data to the put call? Would think of that of the cleaner solution.

**Comment by emilesilvis** [comment]
I'd have to investigate @phoet. The query parameter is the way it's documented in their API docs.

**Comment by phoet** [comment]
yeah, i saw that and i found it a bit weird... anyhow! thx for the contribution, some things:

a) please make it a named parameter
b) add it to all methods that allow the new live collection item, that is post, put, patch
c) let the `request` method handle it, otherwise it will break parameterized urls

**Comment by phoet** [comment]
@emilesilvis do you still want to get this merged?

**Comment by emilesilvis** [comment]
@phoet yes, but needs work. I'll work on this soon.

**Comment by emilesilvis** [comment]
@phoet pushed a commit — not sure if it's the most elegant though! Let me know what you think.

**Comment by phoet** [comment]
@emilesilvis thx for your contribution, i might make an adjustment, but first i need to test if it works as expected. do you need this as a released gem, or are you working with a fork anyways?

**Comment by emilesilvis** [comment]
Thanks @phoet. I don't need a release right now, thanks!

**Pull request merged**
